version: '2'
services:

  dbt:
    build: .
    volumes:
     - .:/usr/app/
    ports:
      - 8080:8080
    environment:
      - DBT_HOST=rc1a-t7cld8ojcr0kovej.mdb.yandexcloud.net
      - DBT_USER=admin
      - DBT_PASSWORD=clickhouse
