config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

clickhouse_starschema:
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: "rc1a-t7cld8ojcr0kovej.mdb.yandexcloud.net"
      port: 8443
      user: "admin"
      password: "clickhouse"
      secure: True
      verify: False
  target: dev
